#! /usr/bin/env python
#
# Support module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Jun 01, 2016 07:36:51 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global domain_low
    domain_low = StringVar()

    global domain_high
    domain_high = StringVar()

    global range_low
    range_low = StringVar()

    global range_high
    range_high = StringVar()


def generateGraph():
    print('calculator_support.generateGraph')
    export_function = w.fucntion_entry.get()
    import calcGraph
    calcGraph.main(export_function)

    from PIL import Image, ImageTk

    image = Image.open("neato.jpg")
    print((w.mpl_target["width"], w.mpl_target["height"]))
    image = image.resize((int(int(w.mpl_target["width"])*0.6), int(int(w.mpl_target["height"])*0.6)))
    
    image.save("output.jpg")
    
    global photo
    photo = ImageTk.PhotoImage(image)
    w.mpl_target.create_image((378/4,265/4),image=photo)

    
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import calculator
    calculator.vp_start_gui()


